const countryData = [
    { country: "United States", currency: "USD", flagCode: "us", alternativeName: "USA",actualCurrency:true },
    { country: "Canada", currency: "CAD", flagCode: "ca" },
    { country: "United Kingdom", currency: "GBP", flagCode: "gb", alternativeName: "UK" },
    { country: "Germany", currency: "EUR", flagCode: "de" },
    { country: "Australia", currency: "AUD", flagCode: "au" },
    { country: "New Zealand", currency: "NZD", flagCode: "nz" },
    { country: "United Arab Emirates", currency: "AED", flagCode: "ae", alternativeName: "UAE" },
    { country: "Bahrain", currency: "USD", flagCode: "bh" },
    { country: "Brazil", currency: "USD", flagCode: "br" },
    
    { country: "China", currency: "USD", flagCode: "cn" },
    { country: "Denmark", currency: "USD", flagCode: "dk" },
    { country: "France", currency: "EUR", flagCode: "fr" },
    
    { country: "Hong Kong", currency: "USD", flagCode: "hk" },
    { country: "Indonesia", currency: "USD", flagCode: "id" },
    { country: "Ireland", currency: "EUR", flagCode: "ie" },
    { country: "Israel", currency: "USD", flagCode: "il" },
    { country: "Italy", currency: "EUR", flagCode: "it" },
    { country: "Japan", currency: "JPY", flagCode: "jp" },
    { country: "Kuwait", currency: "USD", flagCode: "kw" },
    { country: "Malaysia", currency: "USD", flagCode: "my" },
    { country: "Maldives", currency: "USD", flagCode: "mv" },
    { country: "Netherlands", currency: "EUR", flagCode: "nl" },
    
    { country: "Malta", currency: "EUR", flagCode: "mt" },
    { country: "Norway", currency: "USD", flagCode: "no" },
    { country: "Oman", currency: "USD", flagCode: "om" },
    { country: "Philippines", currency: "USD", flagCode: "ph" },
    { country: "Poland", currency: "EUR", flagCode: "pl" },
    { country: "Qatar", currency: "USD", flagCode: "qa" },
    { country: "Russia", currency: "EUR", flagCode: "ru" },
    { country: "Singapore", currency: "SGD", flagCode: "sg" },
    { country: "South Africa", currency: "USD", flagCode: "za" },
    { country: "Spain", currency: "EUR", flagCode: "es" },
    { country: "Sweden", currency: "USD", flagCode: "se" },
    { country: "Switzerland", currency: "USD", flagCode: "ch" },
    { country: "Thailand", currency: "USD", flagCode: "th" },
    
    { country: "Argentina", currency: "USD", flagCode: "ar" },
    { country: "Armenia", currency: "USD", flagCode: "am" },
    { country: "Austria", currency: "EUR", flagCode: "at" },
    { country: "Azerbaijan", currency: "USD", flagCode: "az" },
    { country: "Bangladesh", currency: "USD", flagCode: "bd" },
    { country: "Belgium", currency: "EUR", flagCode: "be" },
    { country: "Bulgaria", currency: "EUR", flagCode: "bg" },
    { country: "Cyprus", currency: "EUR", flagCode: "cy" },
    { country: "Czech Republic", currency: "EUR", flagCode: "cz" },
    { country: "Estonia", currency: "EUR", flagCode: "ee" },
    { country: "Finland", currency: "EUR", flagCode: "fi" },
    { country: "Georgia", currency: "USD", flagCode: "ge" },
    { country: "Greece", currency: "EUR", flagCode: "gr" },
    { country: "Hungary", currency: "EUR", flagCode: "hu" },
    { country: "Iceland", currency: "EUR", flagCode: "is" },
    { country: "Jordan", currency: "USD", flagCode: "jo" },
    { country: "Kazakhstan", currency: "USD", flagCode: "kz" },
    { country: "South Korea", currency: "USD", flagCode: "kr" },
    { country: "Kyrgyzstan", currency: "USD", flagCode: "kg" },
    { country: "Latvia", currency: "EUR", flagCode: "lv" },
    { country: "Liechtenstein", currency: "EUR", flagCode: "li" },
    { country: "Lithuania", currency: "EUR", flagCode: "lt" },
    { country: "Luxembourg", currency: "EUR", flagCode: "lu" },
    { country: "Mexico", currency: "USD", flagCode: "mx" },
    { country: "Morocco", currency: "USD", flagCode: "ma" },
    { country: "Portugal", currency: "EUR", flagCode: "pt" },
    { country: "Romania", currency: "EUR", flagCode: "ro" },
    { country: "Rwanda", currency: "USD", flagCode: "rw" },
    { country: "Saudi Arabia", currency: "USD", flagCode: "sa" },
    { country: "Slovakia", currency: "EUR", flagCode: "sk" },
    { country: "Slovenia", currency: "EUR", flagCode: "si" },
    { country: "Sri Lanka", currency: "USD", flagCode: "lk" },
    { country: "Taiwan", currency: "USD", flagCode: "tw" },
    { country: "Turkey", currency: "EUR", flagCode: "tr" },
    
    { country: "Uruguay", currency: "USD", flagCode: "uy" },
    { country: "Uzbekistan", currency: "USD", flagCode: "uz" },
    { country: "Vietnam", currency: "USD", flagCode: "vn" },
    { country: "Others (USD)", currency: "USD", flagCode: "" },
    { country: "Others (EUR)", currency: "EUR", flagCode: "" }
  ];
  